### ISSUE TITLE
Schaden wird nicht addiert

### ISSUE THREAD

**Issue by enya-w** [Finradon/dsa-ini#7]
Der Schaden wird erst addiert, wenn nach dem DMG Button noch ein anderer Button gedrückt wird.

**Comment by Finradon** [comment]
Probiere Mal: 

1. Zwei Gegner Hinzufügen
2. Den Schaden in die Box eintippen
3. "DMG" drücken
4. "Next" drücken

**Comment by Finradon** [comment]
Ansonsten pulle mal den spätesten Commit auf `main`, da habe ich das ganze noch etwas einfacher geschrieben
